//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoie.Resources.DialogReplies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralReplies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoie.Resources.DialogReplies.General.GeneralReplies", typeof(GeneralReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details &amp; Buy.
        /// </summary>
        public static string DetailsAndBuy {
            get {
                return ResourceManager.GetString("DetailsAndBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahh 😒.
        /// </summary>
        public static string FeedbackA1 {
            get {
                return ResourceManager.GetString("FeedbackA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So and So 😐.
        /// </summary>
        public static string FeedbackA2 {
            get {
                return ResourceManager.GetString("FeedbackA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loved it! 😍.
        /// </summary>
        public static string FeedbackA3 {
            get {
                return ResourceManager.GetString("FeedbackA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you like that collection?.
        /// </summary>
        public static string FeedbackQ {
            get {
                return ResourceManager.GetString("FeedbackQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank your for your feedback!.
        /// </summary>
        public static string FeedbackThanks {
            get {
                return ResourceManager.GetString("FeedbackThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {gender}.
        /// </summary>
        public static string ForGender {
            get {
                return ResourceManager.GetString("ForGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men.
        /// </summary>
        public static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men&apos;s.
        /// </summary>
        public static string Mens {
            get {
                return ResourceManager.GetString("Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more 👁️.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tonight.
        /// </summary>
        public static string Tonight {
            get {
                return ResourceManager.GetString("Tonight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not available in {channel} yet.
        /// </summary>
        public static string Unimplemented {
            get {
                return ResourceManager.GetString("Unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to women.
        /// </summary>
        public static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to women&apos;s.
        /// </summary>
        public static string Womens {
            get {
                return ResourceManager.GetString("Womens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
