//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoie.Resources.DialogReplies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsReplies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoie.Resources.DialogReplies.Settings.SettingsReplies", typeof(SettingsReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current age group setting is:.
        /// </summary>
        public static string AgeGroupCurrent {
            get {
                return ResourceManager.GetString("AgeGroupCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your age group setting has not been set yet..
        /// </summary>
        public static string AgeGroupNotSet {
            get {
                return ResourceManager.GetString("AgeGroupNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your age group setting changed successfully!.
        /// </summary>
        public static string AgeGroupSuccess {
            get {
                return ResourceManager.GetString("AgeGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know we are all kids at heart, but how old are you?.
        /// </summary>
        public static string AgeQ {
            get {
                return ResourceManager.GetString("AgeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below 16.
        /// </summary>
        public static string Below16 {
            get {
                return ResourceManager.GetString("Below16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy 👦.
        /// </summary>
        public static string Boy {
            get {
                return ResourceManager.GetString("Boy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change it?.
        /// </summary>
        public static string ChangePrompt {
            get {
                return ResourceManager.GetString("ChangePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright! Let&apos;s continue from where we left of....
        /// </summary>
        public static string ContinueFlow {
            get {
                return ResourceManager.GetString("ContinueFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I couldn&apos;t save your answer 🙁. Can you tell me once more?.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current gender setting is:.
        /// </summary>
        public static string GenderCurrent {
            get {
                return ResourceManager.GetString("GenderCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gender setting has not been set yet..
        /// </summary>
        public static string GenderNotSet {
            get {
                return ResourceManager.GetString("GenderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a boy or a girl?.
        /// </summary>
        public static string GenderQ {
            get {
                return ResourceManager.GetString("GenderQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gender changed successfully!.
        /// </summary>
        public static string GenderSuccess {
            get {
                return ResourceManager.GetString("GenderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl 👧.
        /// </summary>
        public static string Girl {
            get {
                return ResourceManager.GetString("Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid age..
        /// </summary>
        public static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your location?.
        /// </summary>
        public static string LocationQ {
            get {
                return ResourceManager.GetString("LocationQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location changed successfully!.
        /// </summary>
        public static string LocationSuccess {
            get {
                return ResourceManager.GetString("LocationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to set in now?.
        /// </summary>
        public static string SetPrompt {
            get {
                return ResourceManager.GetString("SetPrompt", resourceCulture);
            }
        }
    }
}
