//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoie.Resources.DialogReplies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonalizationReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalizationReplies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoie.Resources.DialogReplies.Personalization.PersonalizationReplies", typeof(PersonalizationReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know we are all kids at heart, but how old are you?.
        /// </summary>
        public static string AgeQ {
            get {
                return ResourceManager.GetString("AgeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below 16.
        /// </summary>
        public static string Below16 {
            get {
                return ResourceManager.GetString("Below16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy 👦.
        /// </summary>
        public static string Boy {
            get {
                return ResourceManager.GetString("Boy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t get that. Can you tell me once more?.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I couldn&apos;t save your answer 🙁. Can you tell me once more?.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect! Now that I know you better, your outfits will be more personalized! 😁.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string GenderA {
            get {
                return ResourceManager.GetString("GenderA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a girl or a boy?.
        /// </summary>
        public static string GenderQ {
            get {
                return ResourceManager.GetString("GenderQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl 👧.
        /// </summary>
        public static string Girl {
            get {
                return ResourceManager.GetString("Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before I show you some of the best outfits, it would be great to know you a little bit better! ☺.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid answer..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a perfect view!.
        /// </summary>
        public static string LocationA {
            get {
                return ResourceManager.GetString("LocationA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could I please access your location?.
        /// </summary>
        public static string LocationQ {
            get {
                return ResourceManager.GetString("LocationQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright! No problem 🙂 Let&apos;s move on!.
        /// </summary>
        public static string SkipA {
            get {
                return ResourceManager.GetString("SkipA", resourceCulture);
            }
        }
    }
}
