//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoie.Resources.DialogReplies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OccasionReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OccasionReplies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoie.Resources.DialogReplies.Occasion.OccasionReplies", typeof(OccasionReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s make those margaritas count! 🍸.
        /// </summary>
        public static string Cocktail {
            get {
                return ResourceManager.GetString("Cocktail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion suggestions for {occasion}.
        /// </summary>
        public static string CollectionSubtitle {
            get {
                return ResourceManager.GetString("CollectionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no collections found for {occasion} :/.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit and abs!.
        /// </summary>
        public static string Gym {
            get {
                return ResourceManager.GetString("Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t forget to put a smile for your interview!|||Good luck with your interview today!.
        /// </summary>
        public static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Occasion.
        /// </summary>
        public static string OccasionBtn {
            get {
                return ResourceManager.GetString("OccasionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an occasion and I will make you look good {timeOfDay}!|||What are your plans for {timeOfDay}?.
        /// </summary>
        public static string OccasionSelect {
            get {
                return ResourceManager.GetString("OccasionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab your bag! Your dog needs a walk!.
        /// </summary>
        public static string Outdoor {
            get {
                return ResourceManager.GetString("Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s rock that party!|||Let&apos;s get this party started!.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you are!|||Take a look!.
        /// </summary>
        public static string ShowOccasionItems {
            get {
                return ResourceManager.GetString("ShowOccasionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books, notes, and college life awaiting! 🎓|||Final exams week, wear your best! 🎓.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I can’t find any outfit matching this occasion. Want to try another one?|||Sorry if I missed the mark, is there anything else that you would like to try?.
        /// </summary>
        public static string UnknownOccasion {
            get {
                return ResourceManager.GetString("UnknownOccasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View items.
        /// </summary>
        public static string ViewItemsBtn {
            get {
                return ResourceManager.GetString("ViewItemsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like it, put a ring on it! 💍.
        /// </summary>
        public static string Wedding {
            get {
                return ResourceManager.GetString("Wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for tomorrow’s meeting?|||If you want a Maserati, you better work!.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
