//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoie.Resources.Dictionaries.Apparels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Types {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Types() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoie.Resources.Dictionaries.Apparels.Types", typeof(Types).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to σακίδιο πλάτης.
        /// </summary>
        public static string backpack_bag {
            get {
                return ResourceManager.GetString("backpack_bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to σπορ σακάκι.
        /// </summary>
        public static string blazer {
            get {
                return ResourceManager.GetString("blazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to γυναικεία μπλούζα.
        /// </summary>
        public static string blouse {
            get {
                return ResourceManager.GetString("blouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to φούστα μπόχο.
        /// </summary>
        public static string boho_skirt {
            get {
                return ResourceManager.GetString("boho_skirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μπότες.
        /// </summary>
        public static string boots {
            get {
                return ResourceManager.GetString("boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to σουτιέν.
        /// </summary>
        public static string bra {
            get {
                return ResourceManager.GetString("bra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to καζάκα.
        /// </summary>
        public static string camisole {
            get {
                return ResourceManager.GetString("camisole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πλεκτή ζακέτα.
        /// </summary>
        public static string cardigan {
            get {
                return ResourceManager.GetString("cardigan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to παλτό.
        /// </summary>
        public static string coat {
            get {
                return ResourceManager.GetString("coat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to κορσές.
        /// </summary>
        public static string corset {
            get {
                return ResourceManager.GetString("corset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to φόρεμα.
        /// </summary>
        public static string dress {
            get {
                return ResourceManager.GetString("dress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μπλούζα φόρεμα.
        /// </summary>
        public static string dress_shirt {
            get {
                return ResourceManager.GetString("dress_shirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to σαγιονάρες.
        /// </summary>
        public static string flip_flops {
            get {
                return ResourceManager.GetString("flip_flops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τσάντα χειρός.
        /// </summary>
        public static string handbag {
            get {
                return ResourceManager.GetString("handbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τακούνια.
        /// </summary>
        public static string heels {
            get {
                return ResourceManager.GetString("heels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to φούτερ.
        /// </summary>
        public static string hoodie {
            get {
                return ResourceManager.GetString("hoodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to καλσόν.
        /// </summary>
        public static string hose {
            get {
                return ResourceManager.GetString("hose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ζακέτα.
        /// </summary>
        public static string jacket {
            get {
                return ResourceManager.GetString("jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to φούστα τζιν.
        /// </summary>
        public static string jean_skirt {
            get {
                return ResourceManager.GetString("jean_skirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τζιν.
        /// </summary>
        public static string jeans {
            get {
                return ResourceManager.GetString("jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to κόσμημα.
        /// </summary>
        public static string jewelry {
            get {
                return ResourceManager.GetString("jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τσάντα ταχυδρόμου.
        /// </summary>
        public static string messenger_bag {
            get {
                return ResourceManager.GetString("messenger_bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πιτζάμες.
        /// </summary>
        public static string pajamas {
            get {
                return ResourceManager.GetString("pajamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to κιλότα.
        /// </summary>
        public static string panties {
            get {
                return ResourceManager.GetString("panties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peep toes.
        /// </summary>
        public static string peep_toes {
            get {
                return ResourceManager.GetString("peep_toes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πλατφόρμες.
        /// </summary>
        public static string platforms {
            get {
                return ResourceManager.GetString("platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polo.
        /// </summary>
        public static string polo {
            get {
                return ResourceManager.GetString("polo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τσάντα.
        /// </summary>
        public static string purse {
            get {
                return ResourceManager.GetString("purse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to σανδάλια.
        /// </summary>
        public static string sandals {
            get {
                return ResourceManager.GetString("sandals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to κασκόλ.
        /// </summary>
        public static string scarf {
            get {
                return ResourceManager.GetString("scarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to καλσόν.
        /// </summary>
        public static string shapewear {
            get {
                return ResourceManager.GetString("shapewear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πουκάμισο.
        /// </summary>
        public static string shirt {
            get {
                return ResourceManager.GetString("shirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to παπούτσια.
        /// </summary>
        public static string shoes {
            get {
                return ResourceManager.GetString("shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to βερμούδα.
        /// </summary>
        public static string shorts {
            get {
                return ResourceManager.GetString("shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τσάντα ώμου.
        /// </summary>
        public static string shoulder_bag {
            get {
                return ResourceManager.GetString("shoulder_bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to φούστα.
        /// </summary>
        public static string skirt {
            get {
                return ResourceManager.GetString("skirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πιτζάμες.
        /// </summary>
        public static string sleepwear {
            get {
                return ResourceManager.GetString("sleepwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to κάλτσες.
        /// </summary>
        public static string socks {
            get {
                return ResourceManager.GetString("socks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to κοστούμι.
        /// </summary>
        public static string suit {
            get {
                return ResourceManager.GetString("suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to τιράντες.
        /// </summary>
        public static string suspenders {
            get {
                return ResourceManager.GetString("suspenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μαγιώ.
        /// </summary>
        public static string swimwear {
            get {
                return ResourceManager.GetString("swimwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μπλούζα.
        /// </summary>
        public static string t__shirt {
            get {
                return ResourceManager.GetString("t__shirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to γραβάτα.
        /// </summary>
        public static string tie {
            get {
                return ResourceManager.GetString("tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μπλούζα.
        /// </summary>
        public static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to παντελόνι.
        /// </summary>
        public static string trousers {
            get {
                return ResourceManager.GetString("trousers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to χιτώνας.
        /// </summary>
        public static string tunic {
            get {
                return ResourceManager.GetString("tunic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εσώρουχο.
        /// </summary>
        public static string undershirt {
            get {
                return ResourceManager.GetString("undershirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εσώρουχο.
        /// </summary>
        public static string underwear {
            get {
                return ResourceManager.GetString("underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πορτοφόλι.
        /// </summary>
        public static string wallet {
            get {
                return ResourceManager.GetString("wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to νυφικό.
        /// </summary>
        public static string wedding_dress {
            get {
                return ResourceManager.GetString("wedding_dress", resourceCulture);
            }
        }
    }
}
