//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoie.Resources.DialogReplies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreReplies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoie.Resources.DialogReplies.Store.StoreReplies", typeof(StoreReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutBtn {
            get {
                return ResourceManager.GetString("AboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about {store}..
        /// </summary>
        public static string AboutSubtitle {
            get {
                return ResourceManager.GetString("AboutSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to store.
        /// </summary>
        public static string BackToStoreBtn {
            get {
                return ResourceManager.GetString("BackToStoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to betweeen {min} and {max} euros.
        /// </summary>
        public static string BetweenPriceRange {
            get {
                return ResourceManager.GetString("BetweenPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all the available brands in {store}..
        /// </summary>
        public static string BrandsSubtitle {
            get {
                return ResourceManager.GetString("BrandsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string BrandsTitle {
            get {
                return ResourceManager.GetString("BrandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can be found.
        /// </summary>
        public static string CanBeFound {
            get {
                return ResourceManager.GetString("CanBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change filters.
        /// </summary>
        public static string ChangeFiltersBtn {
            get {
                return ResourceManager.GetString("ChangeFiltersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change store.
        /// </summary>
        public static string ChangeStoreBtn {
            get {
                return ResourceManager.GetString("ChangeStoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {store} has no collections yet :/.
        /// </summary>
        public static string CollectionsEmpty {
            get {
                return ResourceManager.GetString("CollectionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us at info@zoie.io and a represenative will contact you..
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactBtn {
            get {
                return ResourceManager.GetString("ContactBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Store Creation.
        /// </summary>
        public static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own messenger store for FREE, by signing up below!!.
        /// </summary>
        public static string CreateSubtitle {
            get {
                return ResourceManager.GetString("CreateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Store!.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer service for {store} store:.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string CustomerServiceBtn {
            get {
                return ResourceManager.GetString("CustomerServiceBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to learn more about {store}?.
        /// </summary>
        public static string CustomerServiceSubtitle {
            get {
                return ResourceManager.GetString("CustomerServiceSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string CustomerServiceTitle {
            get {
                return ResourceManager.GetString("CustomerServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string FilterBrand {
            get {
                return ResourceManager.GetString("FilterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string FilterCategory {
            get {
                return ResourceManager.GetString("FilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter changed successfully!.
        /// </summary>
        public static string FilterChanged {
            get {
                return ResourceManager.GetString("FilterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string FilterColor {
            get {
                return ResourceManager.GetString("FilterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered search 🎨.
        /// </summary>
        public static string FilteredSearch {
            get {
                return ResourceManager.GetString("FilteredSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string FilterGender {
            get {
                return ResourceManager.GetString("FilterGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string FilterPrice {
            get {
                return ResourceManager.GetString("FilterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string FiltersAny {
            get {
                return ResourceManager.GetString("FiltersAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What brand would you like to search for?.
        /// </summary>
        public static string FiltersBrandQ {
            get {
                return ResourceManager.GetString("FiltersBrandQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-shirts.
        /// </summary>
        public static string FiltersCategoryA1 {
            get {
                return ResourceManager.GetString("FiltersCategoryA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trousers.
        /// </summary>
        public static string FiltersCategoryA2 {
            get {
                return ResourceManager.GetString("FiltersCategoryA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresses.
        /// </summary>
        public static string FiltersCategoryA3 {
            get {
                return ResourceManager.GetString("FiltersCategoryA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purses.
        /// </summary>
        public static string FiltersCategoryA4 {
            get {
                return ResourceManager.GetString("FiltersCategoryA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string FiltersCategoryA5 {
            get {
                return ResourceManager.GetString("FiltersCategoryA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackets.
        /// </summary>
        public static string FiltersCategoryA6 {
            get {
                return ResourceManager.GetString("FiltersCategoryA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What clothing type are you looking for?{\n}You can also set your own..
        /// </summary>
        public static string FiltersCategoryQ {
            get {
                return ResourceManager.GetString("FiltersCategoryQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add or change anything?.
        /// </summary>
        public static string FiltersChangeQ {
            get {
                return ResourceManager.GetString("FiltersChangeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string FiltersColorBlack {
            get {
                return ResourceManager.GetString("FiltersColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string FiltersColorBlue {
            get {
                return ResourceManager.GetString("FiltersColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string FiltersColorBrown {
            get {
                return ResourceManager.GetString("FiltersColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string FiltersColorGreen {
            get {
                return ResourceManager.GetString("FiltersColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string FiltersColorOrange {
            get {
                return ResourceManager.GetString("FiltersColorOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string FiltersColorPink {
            get {
                return ResourceManager.GetString("FiltersColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string FiltersColorPurple {
            get {
                return ResourceManager.GetString("FiltersColorPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What color suits you best?{\n}You can also set your own..
        /// </summary>
        public static string FiltersColorQ {
            get {
                return ResourceManager.GetString("FiltersColorQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string FiltersColorRed {
            get {
                return ResourceManager.GetString("FiltersColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string FiltersColorWhite {
            get {
                return ResourceManager.GetString("FiltersColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current filters&apos; selection is:{\n}.
        /// </summary>
        public static string FiltersCurrent {
            get {
                return ResourceManager.GetString("FiltersCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filters have been selected yet. What would you like to add?.
        /// </summary>
        public static string FiltersEmpty {
            get {
                return ResourceManager.GetString("FiltersEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s wear.
        /// </summary>
        public static string FiltersGenderFemale {
            get {
                return ResourceManager.GetString("FiltersGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s wear.
        /// </summary>
        public static string FiltersGenderMale {
            get {
                return ResourceManager.GetString("FiltersGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you looking for men&apos;s or women&apos;s wear?.
        /// </summary>
        public static string FiltersGenderQ {
            get {
                return ResourceManager.GetString("FiltersGenderQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FilterSize {
            get {
                return ResourceManager.GetString("FilterSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the price range you prefer?{\n}You can also set your own..
        /// </summary>
        public static string FiltersPriceQ {
            get {
                return ResourceManager.GetString("FiltersPriceQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the size you want?.
        /// </summary>
        public static string FiltersSizeQ {
            get {
                return ResourceManager.GetString("FiltersSizeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\n}You can also set your own..
        /// </summary>
        public static string FiltersTypeOwn {
            get {
                return ResourceManager.GetString("FiltersTypeOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you are!.
        /// </summary>
        public static string HereYouAre {
            get {
                return ResourceManager.GetString("HereYouAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However you can take a look at the following new products!.
        /// </summary>
        public static string However {
            get {
                return ResourceManager.GetString("However", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More stores.
        /// </summary>
        public static string MoreStores {
            get {
                return ResourceManager.GetString("MoreStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than.
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, continue.
        /// </summary>
        public static string NoContinueBtn {
            get {
                return ResourceManager.GetString("NoContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store currently has no.
        /// </summary>
        public static string NotHave {
            get {
                return ResourceManager.GetString("NotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Store.
        /// </summary>
        public static string ReferralBtn {
            get {
                return ResourceManager.GetString("ReferralBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop in {store} through Zoie&apos;s Store in messenger! Tap the image or click the button below to start shopping..
        /// </summary>
        public static string ReferralSubtitle {
            get {
                return ResourceManager.GetString("ReferralSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {store} Messenger Store on Zoie, an AI Powered Marketplace!.
        /// </summary>
        public static string ReferralTitle {
            get {
                return ResourceManager.GetString("ReferralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reselect store.
        /// </summary>
        public static string ReselectBtn {
            get {
                return ResourceManager.GetString("ReselectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s what I found:.
        /// </summary>
        public static string ResultsFound {
            get {
                return ResourceManager.GetString("ResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string ReturnsPolicyBtn {
            get {
                return ResourceManager.GetString("ReturnsPolicyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn everything you want to know about returns in {store}..
        /// </summary>
        public static string ReturnsPolicySubtitle {
            get {
                return ResourceManager.GetString("ReturnsPolicySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns Policy.
        /// </summary>
        public static string ReturnsPolicyTitle {
            get {
                return ResourceManager.GetString("ReturnsPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisit stores ↩️.
        /// </summary>
        public static string RevisitStores {
            get {
                return ResourceManager.GetString("RevisitStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectBtn {
            get {
                return ResourceManager.GetString("SelectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s pick a store and buy an outfit for today!.
        /// </summary>
        public static string SelectStore {
            get {
                return ResourceManager.GetString("SelectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the available shipping ways, days to deliver and more about {store}..
        /// </summary>
        public static string ShippingSubtitle {
            get {
                return ResourceManager.GetString("ShippingSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string ShippingTitle {
            get {
                return ResourceManager.GetString("ShippingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ShopBtn {
            get {
                return ResourceManager.GetString("ShopBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s get this shopping started! What are you looking for?.
        /// </summary>
        public static string ShopIntro {
            get {
                return ResourceManager.GetString("ShopIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start shopping!.
        /// </summary>
        public static string ShopSubtitle {
            get {
                return ResourceManager.GetString("ShopSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ShopTitle {
            get {
                return ResourceManager.GetString("ShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛍️ Stores.
        /// </summary>
        public static string StoresBtn {
            get {
                return ResourceManager.GetString("StoresBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoie&apos;s marketplace.
        /// </summary>
        public static string TheMarketplace {
            get {
                return ResourceManager.GetString("TheMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m afraid that no.
        /// </summary>
        public static string ThereAreNo {
            get {
                return ResourceManager.GetString("ThereAreNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string TheStore {
            get {
                return ResourceManager.GetString("TheStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of this size.
        /// </summary>
        public static string ThisSize {
            get {
                return ResourceManager.GetString("ThisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all products.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View items.
        /// </summary>
        public static string ViewItemsBtn {
            get {
                return ResourceManager.GetString("ViewItemsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wear.
        /// </summary>
        public static string Wear {
            get {
                return ResourceManager.GetString("Wear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion suggestions by {store}.
        /// </summary>
        public static string WindowCollectionSubtitle {
            get {
                return ResourceManager.GetString("WindowCollectionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window shopping - {gender}.
        /// </summary>
        public static string WindowCollectionTitle {
            get {
                return ResourceManager.GetString("WindowCollectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Collections.
        /// </summary>
        public static string WindowShoppingBtn {
            get {
                return ResourceManager.GetString("WindowShoppingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all the collections created by {store}!.
        /// </summary>
        public static string WindowShoppingSubtitle {
            get {
                return ResourceManager.GetString("WindowShoppingSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Shopping.
        /// </summary>
        public static string WindowShoppingTitle {
            get {
                return ResourceManager.GetString("WindowShoppingTitle", resourceCulture);
            }
        }
    }
}
